export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_ERROR = "ALL_PRODUCT_ERROR"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR"

export const PRODUCT_CATEGORY_REQUEST = "PRODUCT_CATEGORY_REQUEST"
export const PRODUCT_CATEGORY_SUCCESS = "PRODUCT_CATEGORY_SUCCESS"
export const PRODUCT_CATEGORY_ERROR = "PRODUCT_CATEGORY_ERROR"

export const CLEAR_ERROR = "CLEAR_ERROR"

